exports {
  dealers: [
    exports {
      dealerId: 2123452686,
      name: "Bob's Cars",
      vehicles: [Array]
    },
    exports {
      dealerId: 2132904216,
      name: 'House of Wheels',
      vehicles: [Array]
    },
    exports {
      dealerId: 938038473,
      name: "Doug's Doozies",
      vehicles: [Array]
    }
  ]
} Response {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  res: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      decoder: [StringDecoder],
      encoding: 'utf8',
      [Symbol(kPaused)]: false
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      data: [Array],
      error: [Array],
      close: [Function: bound emit]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.coxauto-interview.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 4,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.coxauto-interview.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 4,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      date: 'Sat, 29 Aug 2020 01:33:40 GMT',
      server: 'Kestrel',
      'content-length': '817',
      connection: 'Close'
    },
    rawHeaders: [
      'Content-Type',
      'application/json; charset=utf-8',
      'Date',
      'Sat, 29 Aug 2020 01:33:40 GMT',
      'Server',
      'Kestrel',
      'Content-Length',
      '817',
      'Connection',
      'Close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 200,
    statusMessage: 'OK',
    client: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.coxauto-interview.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(asyncId)]: 4,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET /api/pw88L7pL2Ag/cheat HTTP/1.1\r\n' +
        'Host: api.coxauto-interview.com\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'User-Agent: node-superagent/3.5.2\r\n' +
        'Content-Type: application/json\r\n' +
        'Accept: application/json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/pw88L7pL2Ag/cheat',
      _ended: true,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    text: `{"dealers":[{"dealerId":2123452686,"name":"Bob's Cars","vehicles":[{"vehicleId":443178608,"year":2016,"make":"Honda","model":"Accord"},{"vehicleId":1329311740,"year":2014,"make":"Ford","model":"F150"},{"vehicleId":1359037148,"year":2004,"make":"MINI","model":"Cooper"}]},{"dealerId":2132904216,"name":"House of Wheels","vehicles":[{"vehicleId":1513960900,"year":2013,"make":"Mitsubishi","model":"Gallant"},{"vehicleId":1482916879,"year":2009,"make":"Ford","model":"F150"},{"vehicleId":1623985991,"year":2016,"make":"Kia","model":"Soul"}]},{"dealerId":938038473,"name":"Doug's Doozies","vehicles":[{"vehicleId":1070216503,"year":2016,"make":"Bentley","model":"Mulsanne"},{"vehicleId":287951461,"year":2012,"make":"Nissan","model":"Altima"},{"vehicleId":675432519,"year":1979,"make":"Cheverolet","model":"Corvette"}]}]}`,
    [Symbol(kCapture)]: false
  },
  request: Request {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _agent: false,
    _formData: null,
    method: 'GET',
    url: 'http://api.coxauto-interview.com/api/pw88L7pL2Ag/cheat',
    _header: {
      'user-agent': 'node-superagent/3.5.2',
      'content-type': 'application/json',
      accept: 'application/json'
    },
    header: {
      'User-Agent': 'node-superagent/3.5.2',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    writable: true,
    _redirects: 0,
    _maxRedirects: 5,
    cookies: '',
    qs: {},
    qsRaw: [],
    _redirectList: [],
    _streamRequest: false,
    _timeout: 60000,
    _responseTimeout: 0,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET /api/pw88L7pL2Ag/cheat HTTP/1.1\r\n' +
        'Host: api.coxauto-interview.com\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'User-Agent: node-superagent/3.5.2\r\n' +
        'Content-Type: application/json\r\n' +
        'Accept: application/json\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/pw88L7pL2Ag/cheat',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    protocol: 'http:',
    host: 'api.coxauto-interview.com',
    _endCalled: true,
    _callback: [Function],
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [ClientRequest],
      text: `{"dealers":[{"dealerId":2123452686,"name":"Bob's Cars","vehicles":[{"vehicleId":443178608,"year":2016,"make":"Honda","model":"Accord"},{"vehicleId":1329311740,"year":2014,"make":"Ford","model":"F150"},{"vehicleId":1359037148,"year":2004,"make":"MINI","model":"Cooper"}]},{"dealerId":2132904216,"name":"House of Wheels","vehicles":[{"vehicleId":1513960900,"year":2013,"make":"Mitsubishi","model":"Gallant"},{"vehicleId":1482916879,"year":2009,"make":"Ford","model":"F150"},{"vehicleId":1623985991,"year":2016,"make":"Kia","model":"Soul"}]},{"dealerId":938038473,"name":"Doug's Doozies","vehicles":[{"vehicleId":1070216503,"year":2016,"make":"Bentley","model":"Mulsanne"},{"vehicleId":287951461,"year":2012,"make":"Nissan","model":"Altima"},{"vehicleId":675432519,"year":1979,"make":"Cheverolet","model":"Corvette"}]}]}`,
      [Symbol(kCapture)]: false
    },
    response: [Circular],
    called: true,
    [Symbol(kCapture)]: false
  },
  req: ClientRequest {
    _events: [Object: null prototype] {
      drain: [Function],
      error: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.coxauto-interview.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(asyncId)]: 4,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.coxauto-interview.com',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(asyncId)]: 4,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'GET /api/pw88L7pL2Ag/cheat HTTP/1.1\r\n' +
      'Host: api.coxauto-interview.com\r\n' +
      'Accept-Encoding: gzip, deflate\r\n' +
      'User-Agent: node-superagent/3.5.2\r\n' +
      'Content-Type: application/json\r\n' +
      'Accept: application/json\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    insecureHTTPParser: undefined,
    path: '/api/pw88L7pL2Ag/cheat',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      text: `{"dealers":[{"dealerId":2123452686,"name":"Bob's Cars","vehicles":[{"vehicleId":443178608,"year":2016,"make":"Honda","model":"Accord"},{"vehicleId":1329311740,"year":2014,"make":"Ford","model":"F150"},{"vehicleId":1359037148,"year":2004,"make":"MINI","model":"Cooper"}]},{"dealerId":2132904216,"name":"House of Wheels","vehicles":[{"vehicleId":1513960900,"year":2013,"make":"Mitsubishi","model":"Gallant"},{"vehicleId":1482916879,"year":2009,"make":"Ford","model":"F150"},{"vehicleId":1623985991,"year":2016,"make":"Kia","model":"Soul"}]},{"dealerId":938038473,"name":"Doug's Doozies","vehicles":[{"vehicleId":1070216503,"year":2016,"make":"Bentley","model":"Mulsanne"},{"vehicleId":287951461,"year":2012,"make":"Nissan","model":"Altima"},{"vehicleId":675432519,"year":1979,"make":"Cheverolet","model":"Corvette"}]}]}`,
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      host: [Array],
      'accept-encoding': [Array],
      'user-agent': [Array],
      'content-type': [Array],
      accept: [Array]
    }
  },
  text: `{"dealers":[{"dealerId":2123452686,"name":"Bob's Cars","vehicles":[{"vehicleId":443178608,"year":2016,"make":"Honda","model":"Accord"},{"vehicleId":1329311740,"year":2014,"make":"Ford","model":"F150"},{"vehicleId":1359037148,"year":2004,"make":"MINI","model":"Cooper"}]},{"dealerId":2132904216,"name":"House of Wheels","vehicles":[{"vehicleId":1513960900,"year":2013,"make":"Mitsubishi","model":"Gallant"},{"vehicleId":1482916879,"year":2009,"make":"Ford","model":"F150"},{"vehicleId":1623985991,"year":2016,"make":"Kia","model":"Soul"}]},{"dealerId":938038473,"name":"Doug's Doozies","vehicles":[{"vehicleId":1070216503,"year":2016,"make":"Bentley","model":"Mulsanne"},{"vehicleId":287951461,"year":2012,"make":"Nissan","model":"Altima"},{"vehicleId":675432519,"year":1979,"make":"Cheverolet","model":"Corvette"}]}]}`,
  body: { dealers: [ [Object], [Object], [Object] ] },
  files: undefined,
  buffered: true,
  headers: {
    'content-type': 'application/json; charset=utf-8',
    date: 'Sat, 29 Aug 2020 01:33:40 GMT',
    server: 'Kestrel',
    'content-length': '817',
    connection: 'Close'
  },
  header: {
    'content-type': 'application/json; charset=utf-8',
    date: 'Sat, 29 Aug 2020 01:33:40 GMT',
    server: 'Kestrel',
    'content-length': '817',
    connection: 'Close'
  },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
  type: 'application/json',
  charset: 'utf-8',
  links: {},
  setEncoding: [Function: bound ],
  redirects: [],
  [Symbol(kCapture)]: false
}
